apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "ecr.aws.cloud.qaware.de/v1beta1",
          "kind": "Repository",
          "metadata": {
            "labels": {
              "app": "sample-microservice"
            },
            "name": "repository-sample"
          },
          "spec": {
            "encryptionConfiguration": {
              "encryptionType": "AES256"
            },
            "imageScanningConfiguration": {
              "scanOnPush": true
            },
            "imageTagMutability": "IMMUTABLE"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.10.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: aws-ecr-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Repository is the Schema for the repositories API
      displayName: Repository
      kind: Repository
      name: repositories.ecr.aws.cloud.qaware.de
      version: v1beta1
  description: A K8s operator to manage an AWS ECR Repository as a custom resource.
  displayName: AWS ECR Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ecr.aws.cloud.qaware.de
          resources:
          - repositories
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ecr.aws.cloud.qaware.de
          resources:
          - repositories/finalizers
          verbs:
          - update
        - apiGroups:
          - ecr.aws.cloud.qaware.de
          resources:
          - repositories/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: aws-ecr-operator-controller-manager
      deployments:
      - name: aws-ecr-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                envFrom:
                - secretRef:
                    name: aws-ecr-operator-manager-aws-credentials
                image: lreimer/aws-ecr-operator:1.0.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 100Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: aws-ecr-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: aws-ecr-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - aws
  - aws-ecr
  links:
  - name: AWS ECR Operator
    url: https://github.com/lreimer/aws-ecr-operator
  maintainers:
  - email: mario-leander.reimer@qaware.de
    name: lreimer
  maturity: alpha
  provider:
    name: M.-Leander Reimer
    url: https://github.com/lreimer
  version: 1.0.0
