# permissions for end users to edit repositorylifecycles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repositorylifecycle-editor-role
rules:
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositorylifecycles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositorylifecycles/status
  verbs:
  - get
