# permissions for end users to edit repositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repository-editor-role
rules:
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositories/status
  verbs:
  - get
