# permissions for end users to view repositorylifecycles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repositorylifecycle-viewer-role
rules:
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositorylifecycles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositorylifecycles/status
  verbs:
  - get
