# permissions for end users to edit repositorypolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repositorypolicy-editor-role
rules:
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositorypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecr.aws.cloud.qaware.de
  resources:
  - repositorypolicies/status
  verbs:
  - get
